### ISSUE TITLE
Update to 1.0.1 or 1.02 will stop this to work

### ISSUE THREAD

**Issue by BliXem1** [ekutner/home-connect-hass#317]
In Home Assistant when I update to 1.0.1 or 1.02, it will stop working.

```
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 20:02:06 (6 occurrences)
Last logged: 20:04:49
Error setting up entry Home Connect Appliances for home_connect_alt

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/home_connect_alt/__init__.py", line 138, in async_setup_entry
    homeconnect = await HomeConnect.async_create(auth, delayed_load=True, lang=lang, disabled_appliances=disabled_appliances, sse_timeout=conf[CONF_SSE_TIMEOUT])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HomeConnect.async_create() got an unexpected keyword argument 'sse_timeout'

```
Any idea what is going wrong?

**Comment by bkbartk** [comment]
what HA core version are you using?

**Comment by BliXem1** [comment]
HA Core is: 2024.1.3

**Comment by ekutner** [comment]
I think something went wrong with the upgrade of the add-on. Please remove it from HACS, then delete the folder ```/config/custom_components/home_connect_alt ``` from your home assistant server, then install it again through HACS and see if the issue is still happening.

**Comment by BliXem1** [comment]
Yes, issue is still there.

**Comment by BliXem1** [comment]
Back to 1.0.0 and it works again... Weird.

**Comment by bkbartk** [comment]
strange,
are you using HAOS?
or are you maybe located in china?
I think it's related to this change in 1.0.1
https://github.com/ekutner/home-connect-hass/commit/10495aedf88ea79dc2b4cfac87da14275a09cb89
but I don't know what sse_timeout is.

**Comment by BliXem1** [comment]
Hi,

yes, I am. No I'm not located in China.

**Comment by ekutner** [comment]
@BliXem1 
It looks like main library used by the integration is not properly updating for you. I'm not sure why that is but debugging it may be somewhat involved, so I hope you're up to it.
This is how you would do it with Home Assistant OS (if you have another environment you would have to figure it out for yourself, sorry):
1. Make sure you have a SSH add-on installed in HA. I prefer "Advanced SSH & Web Terminal".
2. Make sure you disabled "Protected Mode" in the add-on settings.
3. Connect to the HA VM using SSH.
4. Run the command: ```docker exec -it homeassistant bash```pip list |grep home-connect```

You should get the output:
```home-connect-async               0.7.16```

But I suspect you have an older version of this package. If you do then try updating it with pip, if it shows the same version number then try removing it with pip and then restart HA and let it reinstall the package automatically. Hopefully that should solve it.

**Comment by BliXem1** [comment]
I reinstall Home assistant and now it works with the latest update :)

**Comment by ekutner** [comment]
Happy to hear that.
